### ISSUE TITLE
关于指数计算方法的问题

### ISSUE THREAD

**Issue by dump-sample** [justoy/sp500_minus_MAGA#1]
如果标普500的计算方法就是加权平均，那么calculate_weighed_value中的total_weight就是100呀，只需要根据sp500.csv这张表中的权重数据就能得到MAGA的加权走势，然后用SPY减去它就得到剩下的，不必再计算一次了。

而且那位的回答确乎是可以复现...因为他是以2018年初的某天为基准，绘图回报率，只不过他的错误在于直接把”SPY的收益率“-”MAGA的收益率“当做”SPY剔除MAGA后的收益率“了。。。。
![incorrect](https://user-images.githubusercontent.com/49090782/86516972-a8b3a880-be57-11ea-9ab4-1e1e6cac7a33.png)

如果正确的计算”SPY剔除MAGA后的收益率“，那么应该是这样
![correct](https://user-images.githubusercontent.com/49090782/86516979-bb2de200-be57-11ea-9af7-47bffd1e68c8.png)

完全没有上面那么夸张

**Comment by justoy** [comment]
是的，直接加权之后加减也可以。

我使用最原始的定义计算是为了防喷。

非常高兴能明白那个错误图是怎么得出的🤣

**Comment by justoy** [comment]
加权加减的一个小问题是，maga的占比是在变化的，比如从15%变成了20%。

当然，这个不会影响结论
